import { Header } from "@/shared/components/shared";

export const metadata = {
    title: "Bag",
    description: "Generated by Next.js",
};

export default function CheckOutLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <>
            <Header
                hasSearch={false}
                hasCart={false}
                className="bg-[#F4F1EE]"
            />
            <main className="min-h-screen bg-[#F4F1EE]">
                <div className="container  px-3 mx-auto pt-10">{children}</div>
            </main>
        </>
    );
}
