import type { Metadata } from "next";
import "../globals.css";
import { Header } from "@/shared/components/shared/header";
import { Suspense } from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function HomeLayout({
    children,
    modal,
}: Readonly<{
    children: React.ReactNode;
    modal: React.ReactNode;
}>) {
    return (
        <>
            <Suspense>
                <Header />
            </Suspense>
            <main>{children}</main>
            {modal}
        </>
    );
}
